### ISSUE TITLE
建议，工作台支持拖拽与布局

### ISSUE THREAD

**Issue by Old-ear** [huajian123/ng-ant-admin#2]
华为云用的gridster2，可以参考

**Comment by huajian123** [comment]
您好，会考虑您的建议

**Comment by smile2014** [comment]
你这模板做的不错

**Comment by huajian123** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huajian123/ng-ant-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月29日(星期一) 下午3:35
***@***.***&gt;;
***@***.******@***.******@***.***&gt;;
主题:&nbsp;Re: [huajian123/ng-ant-admin] 建议，工作台支持拖拽与布局 (#2)





 
你这模板做的不错
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by smile2014** [comment]
要不要考虑把工作流bpmn.js整合进去啊,我之前做了个大概，可以整合进去

**Comment by huajian123** [comment]
@smile2014 会考虑的

**Comment by smile2014** [comment]
我之前做了初版，如果用的上，可以发你

**Comment by huajian123** [comment]
@smile2014 可以考虑提个pr，哈哈
